"use client"
import type { Metadata } from "next";
import "@/styles/admin.css";
import { createContext, useEffect, useState } from "react";
import Link from "next/link";

interface ITeleUser {
  id: string;
  first_name: string;
  last_name: string;
}

interface UserContextProps {
  userData: ITeleUser | null;
}
const UserContext = createContext<UserContextProps | undefined>(undefined);

// export const metadata: Metadata = {
//   title: "Telegram Mini App",
//   description: "Generated by create next app",
// };

export default function AdminLayout({children,}: Readonly<{children: React.ReactNode;}>) {

    const [isDropdownOpen, setIsDropdownOpen] = useState(false);

    const toggleDropdown = () => {
        setIsDropdownOpen(!isDropdownOpen);
    };

    return (
        <div className="flex min-h-screen bg-gray-100">
          {/* Sidebar */}
          <aside className="w-64 bg-gray-800 text-white h-screen">
            <div className="p-4 text-center text-2xl font-bold">Admin</div>
            <ul className="mt-4">
              <li className="px-4 py-2 hover:bg-gray-700">
                <Link href="/">Dashboard</Link>
              </li>
              <li className="px-4 py-2 hover:bg-gray-700">
                <Link href="/users">Users</Link>
              </li>
              <li className="px-4 py-2 hover:bg-gray-700 relative">
                <button
                  onClick={toggleDropdown}
                  className="w-full text-left"
                >
                  경기관리
                  <svg
                    className={`w-5 h-5 inline-block ml-2 transition-transform transform ${
                      isDropdownOpen ? 'rotate-180' : 'rotate-0'
                    }`}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                      clipRule="evenodd"
                    />
                  </svg>
                </button>
                {isDropdownOpen && (
                  <ul className="absolute left-0 mt-2 bg-gray-700 w-full">
                    <li className="px-4 py-2 hover:bg-gray-600">
                      <Link href="/admin/games">경기목록</Link>
                    </li>
                    <li className="px-4 py-2 hover:bg-gray-600">
                      <Link href="/settings/account">경기</Link>
                    </li>
                    <li className="px-4 py-2 hover:bg-gray-600">
                      <Link href="/settings/preferences">경기</Link>
                    </li>
                  </ul>
                )}
              </li>
            </ul>
          </aside>
    
          {/* Main Content */}
          <div className="flex-1 flex flex-col">
            {/* Header */}
            <header className="bg-white shadow p-4 flex justify-between">
              <div>Logo</div>
            </header>
    
            {/* Main Content Area */}
            <main className="flex-1 p-6">
              {children}
            </main>
    
            {/* Footer */}
            <footer className="bg-white shadow p-4 text-center">
              &copy; 2024 Your Company
            </footer>
          </div>
        </div>
      );
    };
